### ISSUE TITLE
Plugin "netlify-plugin-image-optim" internal error

### ISSUE THREAD

**Issue by kartikkasat** [chrisdwheatley/netlify-plugin-image-optim#38]
Plugin "netlify-plugin-image-optim" internal error

TypeError: Cannot set property 'post' of undefined

In "onPostBuild" event in "netlify-plugin-image-optim" from Netlify app
at /opt/build/repo/.netlify/plugins/node_modules/netlify-plugin-image-optim/index.js:38:26
at Array.map ()
at onPostBuild (/opt/build/repo/.netlify/plugins/node_modules/netlify-plugin-image-optim/index.js:34:22)
at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:20:3)
at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
at async process. (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/ipc.js:103:16)

**Comment by BitesizedLion** [comment]
I am also getting this issue.

**Comment by jaymiethomas** [comment]
I'm also getting this exact error since yesterday (previous successful deploy was 27 May 2021 @ 15:30 BST (GMT+1).

If it helps, I'm also running these Netlify plugins:

`Inline critical CSS`
`Minify HTML`
`Sitemap`
`Submit sitemap`

I've had to disable the `Image Optim` plugin for now, with the performance hit that comes with that.

**Comment by Galileosites** [comment]
I've been having this issue for a month now.
I don't know why, because it was working great, and I didn't modify the site, and suddenly stopped working.

Maybe it's a bug in the lastest publish? Idk.

**Comment by jaymiethomas** [comment]
@Galileosites I believe the plugin has remained static. I think something on the underlying Netlify server image has changed and is now incompatible with the plugin.

**Comment by ryanfurrer** [comment]
This is happening to me as well, any fixes on the way?

**Comment by BitesizedLion** [comment]
> This is happening to me as well, any fixes on the way?

As far as I know, no. Just disable the plugin & possibly find an alternative.

**Comment by Edstub207** [comment]
This has been impacting me for ages as well. Not sure why it suddenly broke - thought I'd done something @chrisdwheatley are you aware of this?

**Comment by BitesizedLion** [comment]
> 
> 
> This has been impacting me for ages as well. Not sure why it suddenly broke - thought I'd done something @chrisdwheatley are you aware of this?

Don't bother, author seems inactive, no Github activity since April.
